version: "2"
linters:
  default: none
  enable:
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: instead of using struct literal
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: error strings should not be capitalized or end with punctuation or a newline
      - path: (.+)\.go$
        text: error strings should not end with punctuation or newlines
      - path: (.+)\.go$
        text: error strings should not be capitalized
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
