FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY mc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

RUN  \
     microdnf update -y --nodocs && \
     microdnf install -y ca-certificates --nodocs && \
     microdnf clean all

ENTRYPOINT ["mc"]
