FROM alpine:3.12

MAINTAINER MinIO Inc <dev@min.io>

RUN apk add --no-cache ca-certificates 'curl>7.61.0' && \
    curl -s -q https://dl.minio.io/client/mc/release/linux-amd64/mc -o /usr/bin/mc && \
    chmod +x /usr/bin/mc && \
    curl -s -q -O https://raw.githubusercontent.com/minio/minio/master/CREDITS

ENTRYPOINT ["mc"]
