FROM multiarch/qemu-user-static:x86_64-arm as qemu
FROM arm32v7/alpine:3.12

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin

RUN apk add --no-cache ca-certificates 'curl>7.61.0' && \
    curl -s -q https://dl.minio.io/client/mc/release/linux-arm/mc -o /usr/bin/mc && \
    chmod +x /usr/bin/mc && \
    curl -s -q -O https://raw.githubusercontent.com/minio/minio/master/CREDITS

ENTRYPOINT ["mc"]
