// --------  DO NOT EDIT --------
// This file is autogenerated by genversion.go during the release process.

package main

const mcVersion = "Tue, 22 Sep 2015 21:15:45 GMT"
const mcReleaseTag = "RELEASE.Tue-22-Sep-2015-21-15-45-GMT"
